server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100000000
      maxRequestSize: 200000000
  neo4j:
      url: bolt://192.168.20.153:7687  #3.x
      #url: neo4j://localhost:7687 #4.x
      username: neo4j
      password: 123456
  datasource:
      url: jdbc:mysql://你的ip:3306/kg?useSSL=false&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 你的密码
      type: com.zaxxer.hikari.HikariDataSource
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
file:
  serverurl:  http://localhost:8080
  location : D:\\kgmanager\\csv\\   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/";